# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            citemgr
tagline:          'Manage CTS, CITE Collection and CITE Image repositories.'
description:      'An automated build system (using gradle) for managing CTS, CITE Collection and CITE Image repositories'
baseurl: '/citemgr'


author:
  name:           'Neel Smith'
 

paginate:         5

github:
  repo:           https://github.com/neelsmith/cite

version:          0.12.0

links:
  - title: Live specification
    url: /specs/citeMgr/CiteMgr.html
  - title: API docs
    url: /api
  - title: Github project
    url: https://github.com/cite-architecture/citemgr
    external: true
  - title: CITE architecture home page
    url: http://cite-architecture.github.io/
    external: true
   